logging:
  config: classpath:log4j2-dev.xml
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: filesystem
    password: SZj4EheSpZaBB8ET
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.102.210.203/filesystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT

server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age: -1